include:
  - https://gitlab.com/alex-tu-cc/pipeline/-/raw/master/salsa-ci.yml
  - https://gitlab.com/hustle-ci/pipeline/raw/master/pipeline-jobs.yml

variables:
  RELEASE: 'focal'
  SALSA_CI_AUTOPKGTEST_SETUP_CMDS: |
    sudo apt-get install -y wget snapd software-properties-common &&  add-apt-repository -y -u -s ppa:checkbox-dev/ppa && export DEBIAN_FRONTEND=noninteractive
