#!/bin/bash
set -ex
export DEBIAN_FRONTEND=noninteractive
echo "postfix postfix/mailname string staging-server" | sudo debconf-set-selections
echo "postfix postfix/main_mailer_type string \'Internet Site\'" | sudo debconf-set-selections
